version: '3.9'
services:
  vue:
    image: node:lts
    container_name: vue_spa
    working_dir: /var/www/html/app/
    entrypoint: /bin/bash
    environment:
      - NODE_ENV=development
    ports:
      - "8081:8080"
    volumes:
      - ./vue/:/var/www/html/app/
    tty: true
    networks:
      - pokemon-network
  nginx:
    image: nginx:latest
    container_name: api_srv
    ports:
      - "8080:80"
    volumes:
      - ./api/:/code
      - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
    networks:
      - pokemon-network
  php:
    build: docker/php
    volumes:
      - ./api/:/code
      - ./docker/php/xdebug.ini/:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    environment:
      - XDEBUG_HOST=host.docker.internal
    ports:
      - "5173:5173"
    networks:
      - pokemon-network
  mysql:
    image: mysql:8.0.20
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: pokemon
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker/mysql:/docker-entrypoint-initdb.d
      - ./docker/mysql/data:/var/lib/mysql
    networks:
      - pokemon-network

networks:
  pokemon-network:
    driver: bridge
